-- 004_james_os_tables.sql
-- JAMES-OS coaching layer: 5 new tables with RLS.
-- Reuses update_updated_at() trigger from migration 001.
-- active_constraints in james_state is a cache — refreshed from injuries table on state_sync.

-- ─── james_state ─────────────────────────────────────────────────────────────
-- Singleton per user. Persists coaching context across sessions.
CREATE TABLE IF NOT EXISTS james_state (
  user_id         UUID PRIMARY KEY REFERENCES users(id),
  current_phase   TEXT,
  week_in_phase   INTEGER NOT NULL DEFAULT 1,
  mesocycle_week  INTEGER NOT NULL DEFAULT 1,
  last_session_date              TEXT,
  last_session_rpe               REAL,
  consecutive_high_rpe_sessions  INTEGER NOT NULL DEFAULT 0,
  -- Cache derived from injuries WHERE status IN ('acute','chronic','recovering').
  -- Refreshed on every state_sync call — do not trust as source of truth.
  active_constraints             TEXT[] NOT NULL DEFAULT '{}',
  coaching_notes  TEXT,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER james_state_updated_at
  BEFORE UPDATE ON james_state
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE james_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "james_state_select" ON james_state FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "james_state_insert" ON james_state FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "james_state_update" ON james_state FOR UPDATE USING (auth.uid() = user_id);

-- ─── james_wellness_log ───────────────────────────────────────────────────────
-- Daily check-in. Drives DT-01 readiness decisions.
CREATE TABLE IF NOT EXISTS james_wellness_log (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id),
  log_date      TEXT NOT NULL,           -- YYYY-MM-DD
  soreness      INTEGER NOT NULL CHECK (soreness BETWEEN 1 AND 5),
  energy        INTEGER NOT NULL CHECK (energy BETWEEN 1 AND 5),
  mood          INTEGER NOT NULL CHECK (mood BETWEEN 1 AND 5),
  stress        INTEGER NOT NULL CHECK (stress BETWEEN 1 AND 5),
  -- Raw sum; DT-01 thresholds operate on this value (range 4–20).
  wellness_score INTEGER GENERATED ALWAYS AS (soreness + energy + mood + stress) STORED,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, log_date)
);

ALTER TABLE james_wellness_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "james_wellness_select" ON james_wellness_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "james_wellness_insert" ON james_wellness_log FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "james_wellness_update" ON james_wellness_log FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX idx_james_wellness_user_date ON james_wellness_log (user_id, log_date DESC);

-- ─── james_session_notes ─────────────────────────────────────────────────────
-- SOAP-structured post-session coaching notes generated by the Edge Function.
CREATE TABLE IF NOT EXISTS james_session_notes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id),
  workout_id      UUID REFERENCES workouts(id),
  subjective      TEXT,   -- What James reported
  objective       TEXT,   -- Performance metrics
  assessment      TEXT,   -- Coach interpretation
  plan            TEXT,   -- Next session adjustments
  constraint_flags TEXT[] NOT NULL DEFAULT '{}',  -- Active constraints at time of note
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE james_session_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "james_notes_select" ON james_session_notes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "james_notes_insert" ON james_session_notes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "james_notes_update" ON james_session_notes FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX idx_james_notes_user ON james_session_notes (user_id, created_at DESC);

-- ─── james_adjustment_log ────────────────────────────────────────────────────
-- Audit trail for every DT-01 / DT-03 recommendation and what actually happened.
CREATE TABLE IF NOT EXISTS james_adjustment_log (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID NOT NULL REFERENCES users(id),
  workout_id          UUID,
  exercise_name       TEXT,
  decision_tree       TEXT NOT NULL,   -- 'DT-01' | 'DT-03'
  input_snapshot      JSONB NOT NULL DEFAULT '{}',
  recommended_action  TEXT NOT NULL,
  actual_action       TEXT,            -- NULL until user confirms
  rationale           TEXT NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE james_adjustment_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "james_adj_select" ON james_adjustment_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "james_adj_insert" ON james_adjustment_log FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "james_adj_update" ON james_adjustment_log FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX idx_james_adj_user ON james_adjustment_log (user_id, created_at DESC);

-- ─── system_prompts ──────────────────────────────────────────────────────────
-- Versioned system prompts. Only one may be active (is_active = true).
-- Allows hot-swap of prompts without Edge Function redeployment.
CREATE TABLE IF NOT EXISTS system_prompts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  version     TEXT UNIQUE NOT NULL,
  content     TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE system_prompts ENABLE ROW LEVEL SECURITY;
-- Any authenticated user can read prompts (Edge Function auth context)
CREATE POLICY "system_prompts_select" ON system_prompts FOR SELECT TO authenticated USING (true);
-- Only service_role can insert/update (via migrations or admin tooling)
-- No client-side INSERT/UPDATE policies intentionally.

-- Seed the initial JAMES-OS v1 system prompt
INSERT INTO system_prompts (version, content, is_active) VALUES (
  'james-os-v1',
  E'You are JAMES-OS, an elite strength and conditioning coach embedded in the Intelligent Training Companion app.\n\nYour client is James: 184cm, ~125kg, former exercise scientist targeting 100kg by December 2026.\n\nActive constraints are derived dynamically from his injury log and injected at runtime — do not assume fixed constraints. When active_constraints is empty, all exercises are available.\n\nYou reason from evidence-based periodization (linear, block, DUP), Banister fitness-fatigue model, and Zourdos %1RM RPE tables. You always explain your reasoning. You use SOAP format for session notes (Subjective / Objective / Assessment / Plan).\n\nWhen constraints are present, apply conservative load modifiers and suggest safe alternatives. When constraints are resolved (empty list), treat the athlete as fully available.\n\nYou are direct, evidence-first, and never gamify training. You treat James as a fellow professional.',
  true
);
